"""modifyOtherKeys levels 0-2, captured from xterm 407 (US layout, XTEST key events)."""

import pytest

from bittty import Board, KeyEvent, KeyModifiers
from bittty.connections import MemoryConnection
from bittty.model import XTERM

M = KeyModifiers
# X keysym -> (unshifted key, shifted character)
CHARS = {
    "a": ("a", "A"),
    "z": ("z", "Z"),
    "1": ("1", "!"),
    "2": ("2", "@"),
    "6": ("6", "^"),
    "slash": ("/", "?"),
    "minus": ("-", "_"),
    "space": (" ", " "),
    "bracketleft": ("[", "{"),
    "backslash": ("\\", "|"),
    "grave": ("`", "~"),
}
NAMED = {"Escape": "escape", "Tab": "tab", "BackSpace": "backspace", "Return": "enter"}

XTERM_407 = [
    (0, "a", "", "a"),
    (0, "a", "S", "A"),
    (0, "a", "C", "\x01"),
    (0, "a", "SC", "\x01"),
    (0, "z", "", "z"),
    (0, "z", "S", "Z"),
    (0, "z", "C", "\x1a"),
    (0, "z", "SC", "\x1a"),
    (0, "1", "", "1"),
    (0, "1", "S", "!"),
    (0, "1", "C", "1"),
    (0, "1", "SC", "!"),
    (0, "2", "", "2"),
    (0, "2", "S", "@"),
    (0, "2", "C", "\x00"),
    (0, "2", "SC", "\x00"),
    (0, "6", "", "6"),
    (0, "6", "S", "^"),
    (0, "6", "C", "\x1e"),
    (0, "6", "SC", "\x1e"),
    (0, "slash", "", "/"),
    (0, "slash", "S", "?"),
    (0, "slash", "C", "\x1f"),
    (0, "slash", "SC", "\x7f"),
    (0, "minus", "", "-"),
    (0, "minus", "S", "_"),
    (0, "minus", "C", "-"),
    (0, "minus", "SC", "\x1f"),
    (0, "space", "", " "),
    (0, "space", "S", " "),
    (0, "space", "C", "\x00"),
    (0, "space", "SC", "\x00"),
    (0, "bracketleft", "", "["),
    (0, "bracketleft", "S", "{"),
    (0, "bracketleft", "C", "\x1b"),
    (0, "bracketleft", "SC", "\x1b"),
    (0, "backslash", "", "\\"),
    (0, "backslash", "S", "|"),
    (0, "backslash", "C", "\x1c"),
    (0, "backslash", "SC", "\x1c"),
    (0, "grave", "", "`"),
    (0, "grave", "S", "~"),
    (0, "grave", "C", "\x00"),
    (0, "grave", "SC", "\x1e"),
    (0, "Escape", "", "\x1b"),
    (0, "Escape", "S", "\x1b"),
    (0, "Escape", "C", "\x1b"),
    (0, "Escape", "SC", "\x1b"),
    (0, "Tab", "", "\t"),
    (0, "Tab", "S", "\x1b[Z"),
    (0, "Tab", "C", "\t"),
    (0, "Tab", "SC", "\x1b[Z"),
    (0, "BackSpace", "", "\x7f"),
    (0, "BackSpace", "S", "\x7f"),
    (0, "BackSpace", "C", "\x08"),
    (0, "BackSpace", "SC", "\x08"),
    (0, "Return", "", "\r"),
    (0, "Return", "S", "\r"),
    (0, "Return", "C", "\r"),
    (0, "Return", "SC", "\r"),
    (1, "a", "", "a"),
    (1, "a", "S", "A"),
    (1, "a", "C", "\x01"),
    (1, "a", "SC", "\x01"),
    (1, "z", "", "z"),
    (1, "z", "S", "Z"),
    (1, "z", "C", "\x1a"),
    (1, "z", "SC", "\x1a"),
    (1, "1", "", "1"),
    (1, "1", "S", "!"),
    (1, "1", "C", "\x1b[27;5;49~"),
    (1, "1", "SC", "\x1b[27;6;33~"),
    (1, "2", "", "2"),
    (1, "2", "S", "@"),
    (1, "2", "C", "\x00"),
    (1, "2", "SC", "\x00"),
    (1, "6", "", "6"),
    (1, "6", "S", "^"),
    (1, "6", "C", "\x1e"),
    (1, "6", "SC", "\x1e"),
    (1, "slash", "", "/"),
    (1, "slash", "S", "?"),
    (1, "slash", "C", "\x1f"),
    (1, "slash", "SC", "\x1b[27;6;63~"),
    (1, "minus", "", "-"),
    (1, "minus", "S", "_"),
    (1, "minus", "C", "\x1b[27;5;45~"),
    (1, "minus", "SC", "\x1f"),
    (1, "space", "", " "),
    (1, "space", "S", " "),
    (1, "space", "C", "\x00"),
    (1, "space", "SC", "\x00"),
    (1, "bracketleft", "", "["),
    (1, "bracketleft", "S", "{"),
    (1, "bracketleft", "C", "\x1b"),
    (1, "bracketleft", "SC", "\x1b"),
    (1, "backslash", "", "\\"),
    (1, "backslash", "S", "|"),
    (1, "backslash", "C", "\x1c"),
    (1, "backslash", "SC", "\x1c"),
    (1, "grave", "", "`"),
    (1, "grave", "S", "~"),
    (1, "grave", "C", "\x00"),
    (1, "grave", "SC", "\x1e"),
    (1, "Escape", "", "\x1b"),
    (1, "Escape", "S", "\x1b"),
    (1, "Escape", "C", "\x1b"),
    (1, "Escape", "SC", "\x1b"),
    (1, "Tab", "", "\t"),
    (1, "Tab", "S", "\x1b[Z"),
    (1, "Tab", "C", "\x1b[27;5;9~"),
    (1, "Tab", "SC", "\x1b[Z"),
    (1, "BackSpace", "", "\x7f"),
    (1, "BackSpace", "S", "\x7f"),
    (1, "BackSpace", "C", "\x08"),
    (1, "BackSpace", "SC", "\x08"),
    (1, "Return", "", "\r"),
    (1, "Return", "S", "\x1b[27;2;13~"),
    (1, "Return", "C", "\x1b[27;5;13~"),
    (1, "Return", "SC", "\x1b[27;6;13~"),
    (2, "a", "", "a"),
    (2, "a", "S", "\x1b[27;2;65~"),
    (2, "a", "C", "\x1b[27;5;97~"),
    (2, "a", "SC", "\x1b[27;6;65~"),
    (2, "z", "", "z"),
    (2, "z", "S", "\x1b[27;2;90~"),
    (2, "z", "C", "\x1b[27;5;122~"),
    (2, "z", "SC", "\x1b[27;6;90~"),
    (2, "1", "", "1"),
    (2, "1", "S", "!"),
    (2, "1", "C", "\x1b[27;5;49~"),
    (2, "1", "SC", "\x1b[27;6;33~"),
    (2, "2", "", "2"),
    (2, "2", "S", "\x1b[27;2;64~"),
    (2, "2", "C", "\x1b[27;5;50~"),
    (2, "2", "SC", "\x1b[27;6;64~"),
    (2, "6", "", "6"),
    (2, "6", "S", "\x1b[27;2;94~"),
    (2, "6", "C", "\x1b[27;5;54~"),
    (2, "6", "SC", "\x1b[27;6;94~"),
    (2, "slash", "", "/"),
    (2, "slash", "S", "?"),
    (2, "slash", "C", "\x1b[27;5;47~"),
    (2, "slash", "SC", "\x1b[27;6;63~"),
    (2, "minus", "", "-"),
    (2, "minus", "S", "\x1b[27;2;95~"),
    (2, "minus", "C", "\x1b[27;5;45~"),
    (2, "minus", "SC", "\x1b[27;6;95~"),
    (2, "space", "", " "),
    (2, "space", "S", "\x1b[27;2;32~"),
    (2, "space", "C", "\x1b[27;5;32~"),
    (2, "space", "SC", "\x1b[27;6;32~"),
    (2, "bracketleft", "", "["),
    (2, "bracketleft", "S", "\x1b[27;2;123~"),
    (2, "bracketleft", "C", "\x1b[27;5;91~"),
    (2, "bracketleft", "SC", "\x1b[27;6;123~"),
    (2, "backslash", "", "\\"),
    (2, "backslash", "S", "\x1b[27;2;124~"),
    (2, "backslash", "C", "\x1b[27;5;92~"),
    (2, "backslash", "SC", "\x1b[27;6;124~"),
    (2, "grave", "", "`"),
    (2, "grave", "S", "\x1b[27;2;126~"),
    (2, "grave", "C", "\x1b[27;5;96~"),
    (2, "grave", "SC", "\x1b[27;6;126~"),
    (2, "Escape", "", "\x1b"),
    (2, "Escape", "S", "\x1b[27;2;27~"),
    (2, "Escape", "C", "\x1b[27;5;27~"),
    (2, "Escape", "SC", "\x1b[27;6;27~"),
    (2, "Tab", "", "\t"),
    (2, "Tab", "S", "\x1b[Z"),
    (2, "Tab", "C", "\x1b[27;5;9~"),
    (2, "Tab", "SC", "\x1b[27;6;9~"),
    (2, "BackSpace", "", "\x7f"),
    (2, "BackSpace", "S", "\x1b[27;2;127~"),
    (2, "BackSpace", "C", "\x08"),
    (2, "BackSpace", "SC", "\x1b[27;6;8~"),
    (2, "Return", "", "\r"),
    (2, "Return", "S", "\x1b[27;2;13~"),
    (2, "Return", "C", "\x1b[27;5;13~"),
    (2, "Return", "SC", "\x1b[27;6;13~"),
]


def event(sym, mods):
    modifiers = (M.SHIFT if "S" in mods else M.NONE) | (M.CTRL if "C" in mods else M.NONE)
    if sym in NAMED:
        return KeyEvent(NAMED[sym], modifiers)
    key, shifted = CHARS[sym]
    text = None if modifiers & M.CTRL else (shifted if modifiers & M.SHIFT else key)
    return KeyEvent(key, modifiers, text=text, shifted_key=shifted if modifiers & M.SHIFT else None)


@pytest.mark.parametrize("level,sym,mods,expected", XTERM_407)
def test_modify_other_keys_matches_xterm(level, sym, mods, expected):
    board = Board(model=XTERM)
    wire = MemoryConnection()
    board.host.attach(wire)
    board.feed_host_data(f"\x1b[>4;{level}m".encode())
    board.input_key_event(event(sym, mods))
    assert wire.text == expected
